[package]
name = "pencore"
version = "0.1.0"
edition = "2021"
authors = ["SoftEther VPN Rust Team"]
license = "Apache-2.0"
description = "PenCore module: parsing/validation/serialization of SoftEther 'pencore' field"

[dependencies]
anyhow = "1.0"
